[theme]
primaryColor = "#1E2250"                #Amarelo - similar ao botao
backgroundColor = "#ffffff"             #Amarelo claro para fundo
secondaryBackgroundColor = "#f5f5f5"    # Azul claro para fundo dos widgets
textColor = "#2d377a"                   #Azul - similar ao texto do mercado livre
font = "sans serif"